/* tslint:disable */
/* eslint-disable */
export const __wbg_wasmrenderer_free: (a: number, b: number) => void;
export const wasmrenderer_add_cube: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => number;
export const wasmrenderer_add_sphere: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => number;
export const wasmrenderer_get_object_info: (a: number, b: number, c: number) => void;
export const wasmrenderer_new: () => number;
export const wasmrenderer_object_count: (a: number) => number;
export const wasmrenderer_outline: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number) => void;
export const wasmrenderer_pick: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number) => number;
export const wasmrenderer_remove_object: (a: number, b: number) => void;
export const wasmrenderer_render: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number) => void;
export const wasmrenderer_set_sky: (a: number, b: number) => void;
export const wasmrenderer_set_sky_hdr_bytes: (a: number, b: number, c: number) => void;
export const wasmrenderer_sky_count: (a: number) => number;
export const wasmrenderer_sky_name: (a: number, b: number, c: number) => void;
export const wasmrenderer_update_cube: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => void;
export const wasmrenderer_update_mesh_material: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const wasmrenderer_update_sphere: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => void;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => number;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export: (a: number, b: number, c: number) => void;
export const __wbindgen_export2: (a: number, b: number) => number;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
